---
resources:
- name: repo
  type: git
  source:
   uri: https://github.com/pjadhav01/Concourse.git
   branch: master
  

jobs:
- name: job-test-app
  public: true
  plan:
  - get: repo
    trigger: true
  - task: web-app-tests
    file: repo/devops/build.yml
  - task: deploy-test
    file: repo/devops/deploy.yml


